services:
  api:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/supervisor
    ports:
      - "${API_PORT}:8000"

  db:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: supervisor
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  db_data:
    driver: local
