include:
  - compose.base.yaml

services:
  api:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/supervisor
    ports:
      - "${API_PORT}:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    develop:
      watch:
        - action: sync
          path: .
          target: /app
