services:
  reservation-api:
    build: .
    restart: always
    ports:
      - "8000:8000"

  reservation-db:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: supervisor
      POSTGRES_USER: supervisor
      POSTGRES_PASSWORD: supervisor
    volumes:
      - reservation_db_data:/var/lib/postgresql/data
    ports:
      - "8110:5432"

volumes:
  reservation_db_data:
    driver: local
