include:
  - compose.base.yaml

services:
  api:
    build: .
    image: supervisor-api:latest
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/supervisor
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - db
